title: Agile Approach
description: >-
  theories, methodologies, frameworks, ceremonies, mindset, practices, tools.
baseurl: "/agile-approach"
url: ""

author:
  name: ttych
  website: https://github.com/ttych
  email: thomas.tych@gmail.com
  github:  ttych
  twitter: ThomasTych
  linkedin: thomas-tychensky-60866b1b
  # facebook:
  # pinterest:
  # instagram:
  # googleplus:

google_analytics: UA-136856167-1

show_excerpts: true

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules
  - package.json
  - package-lock.json

# sass:
#   load_paths:
#     - _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
