title: Agile Approach
description: >-
  theories, methodologies, frameworks, ceremonies, mindset, practices, tools.
baseurl: "/agile-approach"
url: ""

email: thomas.tych@gmail.com
github_username:  ttych
#twitter_username: jekyllrb

google_analytics: UA-136856167-1

show_excerpts: true

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules
  - package.json
  - package-lock.json

# sass:
#   load_paths:
#     - _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
